config/routes.rb
Rails.application.routes.draw do

#Public
  root to: 'public#index'
  get 'public/letter'
  get 'public/search'

#Customers
  get 'account', to: 'account/access#menu'
  get 'account/access/menu'
  get 'account/access/login'
  post 'account/access/attempt_login'
  get 'account/access/logout'

  # get 'account/access/new'
  # post 'account/access/create'

  resources :account do
    resources :actors, :films, only: [:index, :show]
  end

  resources :checkout, only: [:new]
  post 'checkout/create'
  post 'rental/create'

  resources :rental_pendings

  resources :rentals

  resources :cart, only: [:index, :show] do
    member do
      get :delete
      get :add
      get :subtract
    end
  end

# Admin
  get 'admin', to: 'admin/access#menu'
  get 'admin/access/menu'
  get 'admin/access/login'
  post 'admin/access/attempt_login'
  get 'admin/access/logout'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  get 'admin/actors/search'
  get 'admin/actors/letter'
  
  get 'admin/customers/search'
  get 'admin/customers/letter'

  get 'admin/films/search'
  get 'admin/films/letter'

  namespace :admin do
    resources :films, :customers, :addresses do
      member do
        get :delete
      end    
    end

    resources :actors do
      member do
        get :delete
        get :films
        post :unlink
        post :link
      end
    end
  end
  
  # post 'admin/actors/:id/unlink/:film_id'


# Staff
  get 'staff', to: 'staff/access#menu'
  get 'staff/access/menu'
  get 'staff/access/login'
  post 'staff/access/attempt_login'
  get 'staff/access/logout'
  
  namespace :staff do 
    resources :main, only: [:index]
    resources :actors, :films, only: [:index, :show]
    resources :orders

    resources :customers, :addresses do 
      member do
        get :delete
      end
    end
  end

# API
  # namespace :api do
  #   resources :actors, :films, :customers, :addresses
  # end

  namespace :api do
    resources :actors do
      get :films
      get :unlink
      get :link
    end

    resources :films do
      get :actors
    end 

    resources :customers, :addresses
  end

  get 'api/search/films'
  get 'api/search/films_letter'
  get 'api/search/actors'
  get 'api/search/actors_letter'

end

app/models/customer.rb
class Customer < ApplicationRecord
	self.table_name = "customer"

	has_secure_password

	# has_one :address, :class_name => "Address", :foreign_key => "address_id"
	# accepts_nested_attributes_for :address
	belongs_to :address

	has_many :rental #2
	has_many :inventory, :through => :rental #4
	has_many :films, :through => :inventory #5 

	has_one :customer_payment_info
	has_many :rental_pendings, :foreign_key => :customer_id

	# has_one :city, :through => 'address'
	# has_one :country, :through => 'city'

	def full_name
		"#{first_name} #{last_name}"
	end


	scope :sorted, lambda { order("first_name ASC")}
	scope :search, lambda {|customer_search| where(["first_name LIKE ?", "#{customer_search}%"]).or(where(["last_name LIKE ?", "#{customer_search}%"])) }
	scope :letter, lambda {|first_letter| where(["first_name LIKE ?", "#{first_letter}%"])}


end

app/controllers/admin/customers_controller.rb
class Admin::CustomersController < ApplicationController

  before_action :confirm_logged_in

  def index
  end

  def search
    @customers = Customer.search(params[:customer_search]).sorted
    if @customers.blank?
      flash[:notice] = "No match found"
    else
      flash[:notice] = nil
    end
  end

  def letter
    @customers = Customer.letter(params[:first_letter])
    if @customers.blank?
      flash[:notice] = "No match for this letter"
    else
      flash[:notice] = nil
    end    
  end

  def show
    @customer = Customer.find(params[:id])
     # [:id] is rails default, not database primary key [:customer_id]
    @address = @customer.address.address
    @city = @customer.address.city.city
    @district = @customer.address.district
    @zip_code = @customer.address.postal_code
    @country = @customer.address.city.country.country
  end

  def new
    @customer = Customer.new
    @address = @customer.build_address
  end

  def create
    @customer = Customer.new(customer_params)
    if @customer.save
    # if Customer.create(customer_params)
      flash[:notice] = "New Customer '#{@customer.full_name}' created."
      redirect_to(admin_customers_path)
    else
      render('new')
    end
  end

  def edit
    @customer = Customer.find(params[:id])
    # @address = Address.all
    @address = @customer.address
    @new_address_id = Address.all.count + 1
  end

  def update
    @customer = Customer.find(params[:id])
    #update
    if @customer.update_attributes(customer_params)
      flash[:notice] = "Customer '#{@customer.full_name}' updated."
      redirect_to(admin_customer_path(@customer))
    else
      render('edit')
    end    
  end

  def delete
    @customer = Customer.find(params[:id])
  end

  def destroy
    @customer = Customer.find(params[:id])
    @customer.destroy
    flash[:notice] = "Customer '#{@customer.full_name}' deleted."
    redirect_to(admin_customers_path)
  end

  private
    def customer_params
      params.require(:customer).permit(:first_name, :last_name, :store_id, :address_id, 
        :address_attributes => [:address, :address2, :district, :city_id, :postal_code, :phone])
    end
end

app/controllers/api/customers_controller.rb
class Api::CustomersController < ApplicationController

	def index
		customers = Customer.sorted
		render json: customers
	end

	def show
		customer = Customer.find(params[:id])
		render json: customer
	end

	def new
		customer = Customer.new
		render json: customer
	end


end

app/controllers/staff/customers_controller.rb
class Staff::CustomersController < ApplicationController

  before_action :staff_logged_in

  def index
    @customers = Customer.search(params[:customer_search]).sorted
  end

  def show
    @customer = Customer.find(params[:id])
    @address = @customer.address.address
    @city = @customer.address.city.city
    @district = @customer.address.district
    @zip_code = @customer.address.postal_code
    @country = @customer.address.city.country.country
  end

  def new
    @customer = Customer.new
    @address = @customer.build_address
  end

  def create
    @customer = Customer.new(customer_params)
    if @customer.save
    # if Customer.create(customer_params)
      flash[:notice] = "New Customer '#{@customer.full_name}' created."
      redirect_to(staff_customers_path)
    else
      render('new')
    end
  end

  def edit
    @customer = Customer.find(params[:id])
    # @address = Address.all
    @address = @customer.address
    @new_address_id = Address.all.count + 1
  end

  def update
    @customer = Customer.find(params[:id])
    #update
    if @customer.update_attributes(customer_params)
      flash[:notice] = "Customer '#{@customer.full_name}' updated."
      redirect_to(staff_customer_path(@customer))
    else
      render('edit')
    end    
  end

  def delete
    @customer = Customer.find(params[:id])
  end

  def destroy
    @customer = Customer.find(params[:id])
    @customer.destroy
    flash[:notice] = "Customer '#{@customer.full_name}' deleted."
    redirect_to(staff_customers_path)
  end

  private
    def customer_params
      params.require(:customer).permit(:first_name, :last_name, :store_id, :address_id, 
        :address_attributes => [:address, :address2, :district, :city_id, :postal_code, :phone])
    end
end

app/helpers/customers_helper.rb
module CustomersHelper
end

app/views/admin/customers/delete.html.erb
<div class="container">

<% @customers_page = 'Customers Delete Page' #refers in layout/admin.html.erb %>

<ul class="nav">
	<li><%= link_to("Back to Customers", admin_customers_path) %></li>
</ul>

<h1>Customer#delete</h1>
<!-- 1st way -->
<%#= form_for(@customer, :url => customer_path(@customer), :method => 'delete') do |customer| %>

<!-- 2nd way -->
<%= form_for([:admin, @customer], method: 'delete') do |customer| %>
	<p>Are you sure you want to delete this customer?</p>
	<p><%= customer.object.full_name %></p>
	<%= customer.submit("Delete", class: 'btn btn-danger') %>
<% end %>

</div>

app/views/admin/customers/edit.html.erb
<div class="container">

<% @customers_page = 'Customers Edit Page' #refers in layout/admin.html.erb %>

<ul class="nav">
	<li><%= link_to("Back to Customers", admin_customers_path) %></li>
</ul>

<%= form_for [:admin, @customer] do |c| %>
	<div class="form-group">
		<label>First Name</label>
		<%= c.text_field(:first_name, class: 'form-control') %>
	</div>
	<div class="form-group">
		<label>Last Name</label>
		<%= c.text_field(:last_name, class: 'form-control') %>
	</div>
	<div class="form-group">
		<label>Store ID</label>
		<%= c.select(:store_id, 1..2, class: 'form-control') %>
	</div>
	
	<div class="form-group">
		<label>Address</label>
		<%= c.fields_for @address do |a| %>
		<%= a.text_field :address, class: 'form-control' %>
	</div>
	<div class="form-group">
		<label>Address 2</label>
		<%= a.text_field :address2, class: 'form-control' %>
	</div>
	<div class="form-group">
		<label>District</label>
		<%= a.text_field :district, class: 'form-control' %>
	</div>
	<div class="form-group">
		<label>City ID</label>
		<%= a.number_field :city_id, class: 'form-control' %>
	</div>
	<div class="form-group">
		<label>Postal Code</label>
		<%= a.text_field :postal_code, class: 'form-control' %>
	</div>
		<% end %>

<%= c.submit class: 'btn btn-warning' %>
<% end %>

</div>

app/views/admin/customers/index.html.erb
<div class="container">

<% if !flash[:notice].blank? %>
	<div class="alert alert-warning">
		<strong><%= flash[:notice] %></strong>
	</div>
<% end %>

<ul class="nav">
	<li><%= link_to("Main Menu", admin_access_menu_path) %></li>
</ul>

<h3>Admin Customers Page</h3>

<select onchange="selectedLetterCustomer(this.value)" class="select-styled">
	<option disabled>Select Letter</option>
	<option>A</option>
	<option>B</option>
	<option>C</option>
	<option>D</option>
	<option>E</option>
	<option>F</option>
	<option>G</option>
	<option>H</option>
	<option>I</option>
	<option>J</option>
	<option>K</option>
	<option>L</option>
	<option>M</option>
	<option>N</option>
	<option>O</option>
	<option>P</option>
	<option>Q</option>
	<option>R</option>
	<option>S</option>
	<option>T</option>
	<option>U</option>
	<option>V</option>
	<option>W</option>
	<option>X</option>
	<option>Y</option>
	<option>Z</option>
</select>
<br/><br/>

<input type="text" onkeyup="searchCustomers(this.value)" class="form-control" placeholder="Search"><br />

<div id="customers"></div>

<h3><%= link_to("Add new customer", new_admin_address_path, :class => 'btn btn-primary btn-block') %></h3>

</div>

app/views/admin/customers/letter.html.erb
<!-- if no match found -->
<% if !flash[:notice].blank? %>
	<div class="alert alert-warning">
		<strong><%= flash[:notice] %></strong>
	</div>
<% end %>


<!-- list of letter matches -->
<table class="table table-striped table-bordered table-hover table-condensed">
	<% @customers.each do |customer|  %>
		<tr>
			<td><%= customer.full_name %></td>
			<td><%= link_to("Show", admin_customer_path(customer)) %></td>
			<td><%= link_to("Edit", edit_admin_customer_path(customer)) %></td>
			<td><%= link_to("Delete", delete_admin_customer_path(customer)) %></td>
		</tr>
	<% end %>
</table>

app/views/admin/customers/new.html.erb
<div class="container">
<% @customers_page = 'New Customers Page' #refers in layout/admin.html.erb %>

<ul class="nav">
	<li><%= link_to("Back to Customers", admin_customers_path) %></li>
</ul>

<h1>Customer#new</h1>

<!-- 1st way -->
<%#= form_for(@customer, :url => customer_path, :method => 'post') do |c| %>

<!-- 2nd way -->
<%= form_for [:admin, @customer] do |a| %>
<table>
	<tr>
		<th>First Name</th>
		<td><%= c.text_field(:first_name) %></td>
	</tr>
	<tr>
		<th>Last Name</th>
		<td><%= c.text_field(:last_name) %></td>
	</tr>
	<tr>
		<th>Store ID</th>
		<td><%= c.select(:store_id, 1..2) %></td>
	</tr>
	
	<%= a.fields_for @address do |a| %>
	<tr>
		<th>Phone Number</th>
		<td><%= a.text_field :phone %></td>
	</tr>
	<tr>
		<th>Address</th>
		<td><%= a.text_field :address %></td>
	</tr>
	<tr>
		<th>Address 2</th>
		<td><%= a.text_field :address2 %></td>
	</tr>
	<tr>
		<th>District</th>
		<td><%= a.text_field :district %></td>
	</tr>
	<tr>
		<th>City ID</th>
		<td><%= a.number_field :city_id %></td>
	</tr>
	<tr>
		<th>Postal Code</th>
		<td><%= a.text_field :postal_code %></td>
	</tr>
	<% end %>

</table><br />

<%= a.submit %>
<% end %>

</div>

app/views/admin/customers/search.html.erb
<!-- if no match found -->
<% if !flash[:notice].blank? %>
	<div class="alert alert-warning">
		<strong><%= flash[:notice] %></strong>
	</div>
<% end %>

<!-- list of found matches -->
<table class="table table-striped table-bordered table-hover table-condensed">
	<% @customers.each do |customer|  %>
		<tr>
				<td><%= customer.full_name %></td>
				<td><%= link_to("Show", admin_customer_path(customer)) %></td>
				<td><%= link_to("Edit", edit_admin_customer_path(customer)) %></td>
				<td><%= link_to("Delete", delete_admin_customer_path(customer)) %></td>
		</tr>
	<% end %>
</table>

app/views/admin/customers/show.html.erb
<div class="container">
<% @customers_page = 'Customers Show Page' #refers in layout/admin.html.erb %>

<ul class="nav">
	<li><%= link_to("Back to Customers", admin_customers_path) %></li>
</ul>

<table class="table table-striped table-bordered table-hover table-condensed">
	<tr>
		<th>Customer's Name</th>
		<td><%= @customer.full_name %></td>		
	</tr>
	<tr>
		<th>Address</th>
		<td><%= @address %></td>
	</tr>
	<tr>
		<th>City</th>
		<td><%= @city %></td>
	</tr>
	<tr>
		<th>District & zip code</th>
		<td><%= @district %> <%= @zip_code %></td>
		
	</tr>
	<tr>
		<th>Country</th>
		<td><%= @country %></td>
	</tr>
</table>

</div>