config/routes.rb
Rails.application.routes.draw do

#Public
  root to: 'public#index'
  get 'public/letter'
  get 'public/search'

#Customers
  get 'account', to: 'account/access#menu'
  get 'account/access/menu'
  get 'account/access/login'
  post 'account/access/attempt_login'
  get 'account/access/logout'

  # get 'account/access/new'
  # post 'account/access/create'

  resources :account do
    resources :actors, :films, only: [:index, :show]
  end

  resources :checkout, only: [:new]
  post 'checkout/create'
  post 'rental/create'

  resources :rental_pendings

  resources :rentals

  resources :cart, only: [:index, :show] do
    member do
      get :delete
      get :add
      get :subtract
    end
  end

# Admin
  get 'admin', to: 'admin/access#menu'
  get 'admin/access/menu'
  get 'admin/access/login'
  post 'admin/access/attempt_login'
  get 'admin/access/logout'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  get 'admin/actors/search'
  get 'admin/actors/letter'
  
  get 'admin/customers/search'
  get 'admin/customers/letter'

  get 'admin/films/search'
  get 'admin/films/letter'

  namespace :admin do
    resources :films, :customers, :addresses do
      member do
        get :delete
      end    
    end

    resources :actors do
      member do
        get :delete
        get :films
        post :unlink
        post :link
      end
    end
  end
  
  # post 'admin/actors/:id/unlink/:film_id'


# Staff
  get 'staff', to: 'staff/access#menu'
  get 'staff/access/menu'
  get 'staff/access/login'
  post 'staff/access/attempt_login'
  get 'staff/access/logout'
  
  namespace :staff do 
    resources :main, only: [:index]
    resources :actors, :films, only: [:index, :show]
    resources :orders

    resources :customers, :addresses do 
      member do
        get :delete
      end
    end
  end

# API
  # namespace :api do
  #   resources :actors, :films, :customers, :addresses
  # end

  namespace :api do
    resources :actors do
      get :films
      get :unlink
      get :link
    end

    resources :films do
      get :actors
    end 

    resources :customers, :addresses
  end

  get 'api/search/films'
  get 'api/search/films_letter'
  get 'api/search/actors'
  get 'api/search/actors_letter'

end

app/models/actor.rb
class Actor < ApplicationRecord
	self.table_name = "actor"

	has_many :film_actor
	has_many :films, :through => :film_actor
	
	accepts_nested_attributes_for :films

	scope :sorted, lambda { order("first_name ASC")}
	scope :search, lambda {|actor_search| where(["first_name LIKE ?", "#{actor_search}%"]).or(where(["last_name LIKE ?", "#{actor_search}%"])) }
	scope :letter, lambda {|first_letter| where(["first_name LIKE ?", "#{first_letter}%"])}

	def full_name
		"#{first_name} #{last_name}"
	end

	validates :first_name, :last_name, 
		presence: true, 
		format: { with: /\A[a-zA-Z ]+\z/, message: "only allows letters" }, 
		length: { maximum: 45 }

end

app/controllers/admin/actors_controller.rb
class Admin::ActorsController < ApplicationController

  before_action :confirm_logged_in

  skip_before_action :verify_authenticity_token
   
  def index
    
  end

  def search
    @actors = Actor.search(params[:actor_search]).sorted
    if @actors.blank?
      flash[:notice] = "No match found"
    else
      flash[:notice] = nil
    end
  end

  def letter
    @actors = Actor.letter(params[:first_letter])
    if @actors.blank?
      flash[:notice] = "No match for this letter"
    else
      flash[:notice] = nil
    end    
  end

  def show
    @actor = Actor.find(params[:id])
    @actor_films = @actor.films

    @films = Film.sorted

    # @film_actor = FilmActor.new
  end

  def films
    @actor = Actor.find(params[:id])
    @found_films = Film.search(params[:film_search]).sorted
  end

  def unlink
    actor = Actor.find(params[:id])
    film = Film.find(params[:film_id])
    
    if actor.films.delete(film)
      redirect_to(admin_actors_path)
    else
      render('index')
    end  
  end

  def link
    actor = Actor.find(params[:id])
    film = Film.find(params[:film_id])

    if actor.films << film
      redirect_to(admin_actors_path)
    end
  end



  def new
    @actor = Actor.new
  end

  def create
    @actor = Actor.new(actor_params)
    if @actor.save
      flash[:notice] = "Actor '#{@actor.full_name}' created. "
      redirect_to(admin_actors_path)
    else
      render('new')
    end
  end

  def edit
    @actor = Actor.find(params[:id])
  end

  def update
    @actor = Actor.find(params[:id])
    if @actor.update_attributes(actor_params)
      flash[:notice] = "Actor '#{@actor.full_name}' updated. "
      redirect_to(admin_actors_path)
    else
      render('edit')
    end      
  end

  def delete
    @actor = Actor.find(params[:id])
  end

  def destroy
    @actor = Actor.find(params[:id])
    if @actor.destroy
      flash[:notice] = "Actor '#{@actor.full_name}' deleted. "
      redirect_to(admin_actors_path)
    end
  end

  private
    def actor_params
      params.require(:actor).permit(:first_name, :last_name)
    end

    def film_actor_params
      params.require(:film_actor).permit(:actor_id, :film_id)
    end

end

app/controllers/api/actors_controller.rb
class Api::ActorsController < ApplicationController

	skip_before_action :verify_authenticity_token

	def films
		actor = Actor.find(params[:actor_id])
		films = actor.films
		if films
			render json: films
		else
			render json: 404
		end
	end

	def link
		actor = Actor.find(params[:actor_id])
		film = Film.find(params[:film_id])
		if actor.films << film
			render json: actor.films
		else
			render json: 404
		end
	end

	def unlink
		actor = Actor.find(params[:actor_id])
		film = Film.find(params[:film_id])
		if actor.films.delete(film)
			render json: actor.films
		else
			render json: 404
		end
	end

	def index
		actors = Actor.sorted
		render json: actors
	end

	def show
		actor = Actor.find(params[:id])
		if actor 
			render json: actor
		else
			render json: 422
		end
	end

	def new
		render json: Actor.new
	end

	def edit
		actor = Actor.find(params[:id])
		render json: actor
	end

	# def create
	# 	actor = Actor.new(actor_params)

	# 	respond_to do |f|
	# 		if actor.save
	# 			f.html { redirect_to [:api, actor]}
	# 			f.js {}
	# 			f.json { render json: @actor, status: :created, location: @actor}
	# 		else
	# 			f.html { render action: 'new'}
	# 			f.json { render json: actor.errors, status: :unprocessable_entity}
	# 		end
	# 	end
	# end

	def create
		actor = Actor.new(actor_params)
		if actor.save
			render json: { message: 'Success'}
			# # redirect_to(staff_actors_path)
			# render status: 200, json: {
			# 	message: 'Successfully created actor.',
			# 	actor: actor
			# }.to_json
		else
			render json: { message: 'Failure' }
			# render("new")
			# render status: 422, json: {
			# 	errors: actor.errors
			# }.to_json
		end
	end

	def update
		actor = Actor.find(params[:id])
		if actor.update(actor_params)
			render json: {
				status: 200,
				message: "Actor successfully updated",
				actor: actor 
			}.to_json
		else
			render json: {
				status: 500,
				message: "Actor failed to update",
				actor: actor
			}
		end
	end

	def destroy
		actor = Actor.find(params[:id])
		actor.destroy
		render json: {
			status: 200,
			message: "Actor successfully deleted"
		}.to_json
	end

	private
		def actor_params
			params.require(:actor).permit(:first_name, :last_name)
		end

end

app/controllers/staff/actors_controller.rb
class Staff::ActorsController < ApplicationController

	before_action :staff_logged_in

	def index
		@actors = Actor.sorted
	end

	def show
		@actor = Actor.find(params[:id])
		@actor_films = @actor.films
	end

end

app/helpers/actors_helper.rb
module ActorsHelper
end

app/views/admin/actors/add_film.html.erb
<h1>Add#Films</h1>

<h3><%= link_to("Back to Actors", admin_actors_path) %></h3>

<h3><%= @actor.full_name %> played in the following films:</h3>

<table>
	<% @actor_films.each do |m| %>
		<tr>
			<td><%= m.title %></td>
		</tr>
	<% end %>
</table>

<h2>Add films:</h2>

app/views/admin/actors/delete.html.erb
<div class="container">

<ul class="nav">
	<li><%= link_to("Back to Actors", admin_actors_path) %></li>
</ul>

<%= form_for([:admin, @actor], :method => 'delete') do |a| %>
	<p>Are you sure to delete actor <%= @actor.full_name %>?</p>

	<p><%= a.submit("Delete", class: 'btn btn-danger btn-block') %></p>

<% end %>

</div>

app/views/admin/actors/edit.html.erb
<div class="container">

<ul class="nav">
	<li><%= link_to("Back to Actors", admin_actors_path) %></li>
</ul>


<%= form_for [:admin, @actor] do |a| %>
	<div class="form-group">
		<label> Actor's First Name</label>
		<%= a.text_field(:first_name, class: 'form-control') %>
	</div>
	<div class="form-group">
		<label> Actor's Last Name</label>
		<%= a.text_field(:last_name, class: 'form-control') %>
	</div>
<%= a.submit class: 'btn btn-warning' %>
<% end %>

</div>

app/views/admin/actors/films.html.erb
<div class="list-group">
	<% @found_films.each do |film|  %>
		<div onclick="link(<%= @actor.actor_id %>, <%= film.film_id %>)" class="list-group-item" >
			<%= film.title %></div>
	<% end %>
</div>

app/views/admin/actors/index.html.erb
<div class="container">

<% if !flash[:notice].blank? %>
	<div class="alert alert-warning">
		<strong><%= flash[:notice] %></strong>
	</div>
<% end %>

<ul class="nav">
	<li><%= link_to("Main Menu", admin_access_menu_path) %></li>
</ul>

<h3>Admin Actors Page</h3>

<select onchange="selectedLetter(this.value)" class="select-styled">
	<option disabled>Select Letter</option>
	<option>A</option>
	<option>B</option>
	<option>C</option>
	<option>D</option>
	<option>E</option>
	<option>F</option>
	<option>G</option>
	<option>H</option>
	<option>I</option>
	<option>J</option>
	<option>K</option>
	<option>L</option>
	<option>M</option>
	<option>N</option>
	<option>O</option>
	<option>P</option>
	<option>Q</option>
	<option>R</option>
	<option>S</option>
	<option>T</option>
	<option>U</option>
	<option>V</option>
	<option>W</option>
	<option>X</option>
	<option>Y</option>
	<option>Z</option>
</select>
<br/><br/>

<input type="text" onkeyup="searchActors(this.value)" class="form-control" placeholder="Search"><br />

<div id="actors"></div>

<%= link_to("Add new actor", new_admin_actor_path, :class => 'btn btn-primary btn-block') %>

</div>

app/views/admin/actors/letter.html.erb
<!-- if no match found -->
<% if !flash[:notice].blank? %>
	<div class="alert alert-warning">
		<strong><%= flash[:notice] %></strong>
	</div>
<% end %>


<!-- list of letter matches -->
<table class="table table-striped table-bordered table-hover table-condensed">
	<% @actors.each do |actor|  %>
		<tr>
			<td><%= actor.full_name %></td>
			<td><%= link_to("Show", admin_actor_path(actor)) %></td>
			<td><%= link_to("Edit", edit_admin_actor_path(actor)) %></td>
			<td><%= link_to("Delete", delete_admin_actor_path(actor)) %></td>
		</tr>
	<% end %>
</table>

app/views/admin/actors/new.html.erb
<div class="container">

<ul class="nav">
	<li><%= link_to("Back to Actors", admin_actors_path) %></li>
</ul>


<%= form_for [:admin, @actor] do |a| %>

	<div class="form-group">
		<label>Actor's First Name</label>
		<%= a.text_field(:first_name, class: 'form-control', placeholder: 'Enter First Name') %>
	</div>
	<div class="form-group">
		<label>Actor's Last Name</label>
		<%= a.text_field(:last_name, class: 'form-control', placeholder: 'Enter Last Name') %>
	</div>
<%= a.submit class: 'btn btn-primary btn-lg btn-block' %>
<% end %>




</div>

app/views/admin/actors/search.html.erb
<!-- if no match found -->
<% if !flash[:notice].blank? %>
	<div class="alert alert-warning">
		<strong><%= flash[:notice] %></strong>
	</div>
<% end %>

<!-- list of found matches -->
<table class="table table-striped table-bordered table-hover table-condensed">
	<% @actors.each do |actor|  %>
		<tr>
				<td><%= actor.full_name %></td>
				<td><%= link_to("Show", admin_actor_path(actor)) %></td>
				<td><%= link_to("Edit", edit_admin_actor_path(actor)) %></td>
				<td><%= link_to("Delete", delete_admin_actor_path(actor)) %></td>
		</tr>
	<% end %>
</table>

app/views/admin/actors/show.html.erb
<div class="container">

<ul class="nav">
	<li><%= link_to("Back to Actors", admin_actors_path) %></li>
</ul>

<label>Add movies</label><br />
<input type="text" onkeyup="searchMovies(this.value, <%= @actor.actor_id %>)" class="form-control"><br />

<div id="films"></div>

<h3><%= @actor.full_name %> played in <%= @actor_films.count %> movies</h3>

<table class="table table-striped table-bordered table-hover table-condensed">
	
	<% @actor_films.each do |af| %>
		<tr>
			<td><%= af.title %></td>
			<td onclick="unlink(<%= @actor.actor_id %>,<%= af.film_id %>)" class="btn btn-danger btn-sm">Remove</td>
		</tr>
	<% end %>
</table>

</div>