config/routes.rb
Rails.application.routes.draw do

#Public
  root to: 'public#index'
  get 'public/letter'
  get 'public/search'

#Customers
  get 'account', to: 'account/access#menu'
  get 'account/access/menu'
  get 'account/access/login'
  post 'account/access/attempt_login'
  get 'account/access/logout'

  # get 'account/access/new'
  # post 'account/access/create'

  resources :account do
    resources :actors, :films, only: [:index, :show]
  end

  resources :checkout, only: [:new]
  post 'checkout/create'
  post 'rental/create'

  resources :rental_pendings

  resources :rentals

  resources :cart, only: [:index, :show] do
    member do
      get :delete
      get :add
      get :subtract
    end
  end

# Admin
  get 'admin', to: 'admin/access#menu'
  get 'admin/access/menu'
  get 'admin/access/login'
  post 'admin/access/attempt_login'
  get 'admin/access/logout'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  get 'admin/actors/search'
  get 'admin/actors/letter'
  
  get 'admin/customers/search'
  get 'admin/customers/letter'

  get 'admin/films/search'
  get 'admin/films/letter'

  namespace :admin do
    resources :films, :customers, :addresses do
      member do
        get :delete
      end    
    end

    resources :actors do
      member do
        get :delete
        get :films
        post :unlink
        post :link
      end
    end
  end
  
  # post 'admin/actors/:id/unlink/:film_id'


# Staff
  get 'staff', to: 'staff/access#menu'
  get 'staff/access/menu'
  get 'staff/access/login'
  post 'staff/access/attempt_login'
  get 'staff/access/logout'
  
  namespace :staff do 
    resources :main, only: [:index]
    resources :actors, :films, only: [:index, :show]
    resources :orders

    resources :customers, :addresses do 
      member do
        get :delete
      end
    end
  end

# API
  # namespace :api do
  #   resources :actors, :films, :customers, :addresses
  # end

  namespace :api do
    resources :actors do
      get :films
      get :unlink
      get :link
    end

    resources :films do
      get :actors
    end 

    resources :customers, :addresses
  end

  get 'api/search/films'
  get 'api/search/films_letter'
  get 'api/search/actors'
  get 'api/search/actors_letter'

end

app/models/rental.rb
class Rental < ApplicationRecord
	self.table_name = "rental"
	:rental_date
	belongs_to :inventory #1
	belongs_to :customer #2
	has_many :film, :through => :inventory
end

app/controllers/rentals_controller.rb
class RentalsController < ApplicationController

	def new
		if session[:customer_id]
			@customer = Customer.find(session[:customer_id])

			@pending_process = RentalPending.new()


			# @rental = Rental.new
			if session[:pending_rent]
				@hash = Hash.new(0)
				session[:pending_rent].each do |film|
					@hash[Film.find(film)] += 1
				end
			else
			end
		else
			redirect_to(account_access_login_path)
		end
	end

	def create
		@rental = Rental.new(rental_parameters)
		if @rental.save
			# redirect_to(ordered_checkout)
			flash[:notice] = "Your order has been successfully submitted"
		else
		end
	end

	private
		def rental_parameters
			params.require(:rental).permit(:rental_date, :inventory_id, :customer_id, :staff_id)
		end

end

app/views/rentals/new.html.erb
<div class="container">
	
<%  if @customer %>
	<h4><%= link_to(@customer.username, account_access_menu_path(@customer)) %></h4>
<% end %>

<h4><%= link_to("Cart", cart_index_path) %></h4>

<h5><%= link_to("Rent more movies", root_path) %></h5>

<h3>Shipping Address</h3>
<div class="form_group">
	<p><%= @customer.full_name %></p>
	<p><%= @customer.address.address %></p>
	<p><%= @customer.address.city.city %></p>
	<p><%= @customer.address.postal_code %></p>		
</div>

<h3>Payment Information:</h3>
	<p><%= @customer.customer_payment_info.card_number %></p>

<h3>Order Summary:</h3>


<table class="table">
	<th>Film Name</th>
	<th>Rental Rate</th>
	<th>Quantity</th>
	<th>Amount</th>
	
	<% total = 0 %>
	<% @hash.each do |film, amount| %>
		<tr>
			<td><%= film.title %></td>
			<td>$<%= film.rental_rate %></td>
			<td><%= amount %></td>
			<td>$<%= dollars = film.rental_rate * amount  %></td>
					<% total += dollars	%>
		</tr>
	<% end %>
		<tr>
			<td>TOTAL</td>
			<td></td>
			<td></td>
			<td>$<%= total %></td>
		</tr>


</table>

	<%= form_for @pending_process do |r| %>
		<%= r.submit("Place Order", class: 'btn btn-primary btn-block') %>
	<% end %>


</div>